package com.taller.app.recapture

enum class RecaptureReason {
    ATTENTION_LOST_BETWEEN_QUESTIONS,
    ATTENTION_LOST_AFTER_FEEDBACK_COOLDOWN,
    ATTENTION_LOST_BEFORE_ACTIVITY_START,
    ATTENTION_LOST_DURING_ALLOWED_WINDOW,
    LIMIT_REACHED,
    COOLDOWN_ACTIVE,
    SUPPRESSED_BY_FLOW_PHASE,
    CHILD_RETURNED_BEFORE_SPEECH,
    CHILD_RETURNED_DURING_SPEECH,
    CHILD_RETURNED_AFTER_SPEECH,
    NO_RETURN_AFTER_FINAL_RECAPTURE
}
