package com.taller.app.ui

enum class Screen {
    HOME,
    MAIN,
    FACE_DETECTION,
    SPEECH_TEST,
    SEMANTIC_TEST,
    TEACHER_ACTIVITIES,
    TEACHER_QUESTIONS,
    TOY_VOICE_SETTINGS,
    BIMODAL_INTERACTION,
    CLASSIC_TIMER_INTERACTION,
    CLASSIC_SEVEN_FACE,
    METRICS_EXPORT
}
